Yoast/developer-docs

docs/features/schema/api.md
=> Change Schema API docs

docs/standards/cheatsheets.md, docs/standards/coding-guidelines-and-principles.md, docs/standards/development-setup.md, docs/standards/development-tools.md, docs/standards/overview.md, docs/standards/productivity-tips-and-tricks.md, docs/standards/running-unit-tests-code-style-checks-and-linters.md, docs/standards/version-control-conventions.md
This PR introduces documentation regarding development tools, configs, conventions etc. categorized under "Standards"
=> Adds missing Standards documentation

docs/features/meta-robots/functional-specification.md, docs/features/schema/api.md, docs/features/schema/integration-guidelines.md, docs/features/schema/pieces/webpage.md
This PR syncs recent changes done on the current version of developer.yoast.com, to these docs.
=> Syncs minor changes from current developer.yoast.com

docs/features/schema/api.md, docs/features/schema/background.md, docs/features/schema/functional-specification.md, docs/features/schema/integration-guidelines.md, docs/features/schema/pieces/aggregateoffer.md, docs/features/schema/pieces/article.md, docs/features/schema/pieces/breadcrumb.md, docs/features/schema/pieces/comment.md, docs/features/schema/pieces/howto.md, docs/features/schema/pieces/image.md, docs/features/schema/pieces/localbusiness.md, docs/features/schema/pieces/offer.md, docs/features/schema/pieces/organization.md, docs/features/schema/pieces/person.md, docs/features/schema/pieces/postaladdress.md, docs/features/schema/pieces/product.md, docs/features/schema/pieces/question.md, docs/features/schema/pieces/review.md, docs/features/schema/pieces/searchaction.md, docs/features/schema/pieces/video.md, docs/features/schema/pieces/webpage.md, docs/features/schema/pieces/website.md, docs/features/schema/plugins/local-seo.md, docs/features/schema/plugins/yoast-seo.md, docs/features/schema/technology-approach.md, docs/standards/setting-up-integration-tests-for-the-plugins.md, docs/yoast-seo-product-sheet.md
Docusaurus' auto-detection screws this up otherwise. Also fixes some broken edit URL links.
=> Added custom meta descriptions to docs that import React components

docs/features/meta-tags/api.md, docs/features/meta-tags/extensions-and-addons.md, docs/features/meta-tags/functional-specification.md, docs/features/meta-tags/overview.md
Add the relatively new Meta tags documentation.
=> Added meta tags documentation

docs/customization/yoast-seo/adding-custom-data-analysis.md
This PR explains how users can add custom data to the text analysis.
=> Added an example on how to extend YoastSEO.js' data analysis

docs/customization/yoast-seo/indexables-cli.md
This PR adds a doc regarding the usage of the indexables CLI command.
=> Added indexables CLI docs

docs/features/schema/api.md
Fixes https://github.com/Yoast/Support/issues/200
=> Make Schema example better

docs/features/opengraph/api/changing-og-locale-output.md, docs/features/opengraph/api/overview.md, docs/features/opengraph/extensions-and-addons.md, docs/features/opengraph/functional-specification.md, docs/features/schema/integration-guidelines.md, docs/features/seo-tags/canonical-urls/api.md, docs/overview.md
Added some more content/context to the homepage.
Made title/heading formats more consistent.
=> Homepage updates, and some minor tidying

docs/features/schema/api.md
Fixed broken link and changed references to the proper classes.
=> Updated section regarding adding/removing graph pieces

docs/customization/apis/overview.md, docs/customization/apis/rest-api.md, docs/customization/apis/surfaces-api.md
Duplicated from release blog posts, added into a new section.
Can we add a sidebar nav for these in Customization, please?
=> Add API docs

docs/features/schema/overview.md
Hello,
This commit is just to fix the broken links on this page: https://developer.yoast.com/features/schema/overview
=> fix(docs): update broken links

docs/customization/local-seo/changing-location-post-type.md, docs/standards/overview.md, docs/standards/reindex-indexables.md
Adds a page describing the upcoming `wpseo_local_post_type` filter.
=> Added page describing the wpseo_local_post_type filter

docs/standards/using-composer.md
This is an updated version of the docs we had on the Wiki.
=> Added docs regarding using Composer

docs/customization/local-seo/changing-location-post-type.md, docs/customization/local-seo/changing-location-url-google-maps.md, docs/customization/yoast-seo-premium/disabling-automatic-redirects-notifications.md, docs/customization/yoast-seo/adding-custom-data-analysis.md, docs/features/opengraph/api/changing-og-locale-output.md, docs/features/schema/api.md, docs/features/schema/integration-guidelines.md, docs/features/seo-tags/canonical-urls/api.md, docs/features/seo-tags/meta-robots/functional-specification.md, docs/features/xml-sitemaps/functional-specification.md, docs/standards/coding-guidelines-and-principles.md
This updates a bunch of code blocks to make sure they work and that they adhere to our own coding standards.
=> Updated code-style, docblocks and fixed broken examples

docs/overview.md
Requires https://github.com/Yoast/developer-site/pull/55
=> Reverted ID for overview page

docs/customization/apis/metadata-api.md
This PR expands the Metadata API page by adding a few more examples.
I've also slightly altered some other parts of the text to improve the overall flow of the text.
=> Expand metadata API examples

docs/features/xml-sitemaps/api.md
Added a few more examples.
Also, some of the existing examples were lacking some documentation.
=> Added more examples and fixed some of the existing ones

docs/features/seo-tags/canonical-urls/overview.md, docs/features/xml-sitemaps/overview.md
Updated overview docs with links to feature pages
=> Added feature links

docs/standards/development-setup.md
Also rewrote the part regarding the standalone development of the monorepo to better fit with the tone of the section.
=> Added instructions on how to properly link the monorepo to the plugin

docs/features/opengraph/api/changing-og-locale-output.md
=> Fixed example on how to remove the locale presenter

docs/features/rss-feeds/functional-specification.md
Also fixes some wording to remain consistent with everything else.
=> Fixed some parts of the RSS feed spec, such as sidebar label

docs/features/schema/plugins/local-seo.md, docs/features/schema/plugins/news-seo.md, docs/features/schema/plugins/video-seo.md, docs/features/schema/plugins/woocommerce-seo.md, docs/features/schema/plugins/yoast-seo.md
Adds separate sections with links that point to the various pieces, related to the current plugin page.
Fixes https://yoast.atlassian.net/browse/DEVREL-56
Fixes https://yoast.atlassian.net/browse/DEVREL-59
=> Adds links to pieces

docs/standards/coding-guidelines-and-principles.md, docs/standards/development-tools.md, docs/standards/running-unit-tests-code-style-checks-and-linters.md
This PR adds some missing information that was still present on the Wiki.
=> Add missing developer setup information

docs/standards/development-setup.md, docs/standards/setting-up-integration-tests-for-the-plugins.md
Moved some of the PHPunit configuration instructions so everything is more concentrated in one place instead of spread out across pages.
=> Moved PHPunit docs a bit and reformulated some of the steps

docs/customization/local-seo/changing-location-post-type.md, docs/development/environment/setup-plugin-integration-tests.md, docs/development/environment/setup.md, docs/development/standards/coding-guidelines-and-principles.md, docs/features/installation/using-composer.md, docs/features/schema/api.md, docs/features/schema/functional-specification.md, docs/features/schema/technology-approach.md, docs/features/seo-tags/meta-robots/overview.md, docs/features/wp-cli/reindex-indexables.md, docs/overview.md
This PR is part of https://github.com/Yoast/developer-site/pull/79 and replaces https://github.com/Yoast/developer-docs/pull/88
=> Fixed all docs to utilize alpha 65 features

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
This PR introduces some templates and other handy docs to be used when contributing to the project.
=> Introduce a PR template, CoC and contribution guide

docs/customization/yoast-seo/adding-custom-assessments.md
This PR introduces a new article on how to create a custom webworker that can be registered with Yoast SEO.
=> Introduce example webworker project

docs/customization/yoast-seo/changing-enhanced-slack-sharing.md
* Adds docs for the new Enhanced Slack sharing feature
*
=> Add slack sharing dev docs

docs/features/schema/plugins/news-seo.md
* Fixes the Schema docs for News SEO to reflect changes made in News SEO.
*
=> Fixed the Schema docs for News SEO to reflect changes

docs/features/schema/api.md
* Fixes a faulty reference in a code example regarding the Schema API.
*
=> Fixed faulty reference in code example

docs/customization/yoast-seo/filtering-yoast-blocks.md
* Adds an example of an approach on how to filter out / include, particular blocks in the editor.
* 
Fixes #97
=> Added an approach via JavaScript instead of PHP

docs/development/environment/generating-unit-test-template.md
* Adds documentation for the newly introduced unit test generator.
* N/A
=> Added documentation for the unit test generator.

docs/development/environment/setup-plugin-integration-tests.md
* Adds missing information regarding accessing the admin area of the integration test environment.
*
=> Added extra information regarding accessing the admin of integration test environments

docs/customization/yoast-seo/filters/capability-roles-filter.md
* Introduces doc regarding the `{$capability}_roles` filter.
*
=> Introduced docs related to the capability_roles filter

docs/development/standards/phpunit-best-practices.md
* Migrated PhpUnit coding standards from the Wiki to here
*
=> Migrated PhpUnit coding standards from the Wiki to here

docs/development/standards/writing-issues-and-pull-requests.md
* Introduces doc regarding writing standards for issues and PRs.
*
=> Added doc regarding standards used when writing issues/PRs

docs/features/schema/api.md
* Adds an example to the Schema API page on how to exclude pieces from the Schema output.
*
=> Added example on removing Schema pieces

docs/customization/yoast-seo/wp-get-environment-type-in-yoast-seo.md
Add documentation for [`wp_get_environment_type()`](https://developer.wordpress.org/reference/functions/wp_get_environment_type/)
*
=> Add documentation for `wp_get_environment_type()`

docs/development/environment/tools.md
* Moved the Debug Bar explanation to the tools section.
*
=> Added Debug Bar to the tools section

docs/customization/local-seo/changing-organization-url-in-schema.md
* Adds documentation regarding new filter `yoast-local-seo-schema-organization-url` for Organization URL in Local SEO 13.9.
* [] I have altered a filename
* [] I have adjusted the ID and editUrl properties accordingly and updated all internal links. 
*
=> Added doc regarding new filter for Organization URL in Local SEO 13.9

docs/customization/yoast-seo/filters/primary-term-taxonomies-filter.md
* Adds documentation regarding the `wpseo_primary_term_taxonomies` filter.
*
=> Add primary term taxonomies filter

docs/customization/yoast-seo/filters/cornerstone-post-types-filter.md
* Adds documentation regarding the `wpseo_cornerstone_post_types` filter.
*
=> Added documentation regarding the cornerstone post type filter

docs/customization/yoast-seo/filters/markdown-enabled-filter.md
* Adds documentation for the `wpseo_is_markdown_enabled` filter
*
=> Add documentation for the markdown enabled filter

docs/features/schema/plugins.md, docs/features/schema/plugins/yoast-seo-shopify.md
Add documentation for Yoast SEO for Shopify schema output
* [NA] I have altered a filename
* [NA] I have adjusted the ID and editUrl properties accordingly and updated all internal links. 
* 
* [NA] I have tested my changes
=> Add documentation for Yoast SEO for Shopify schema output

docs/customization/yoast-seo/filters/filtering-yoast-seo-indexables.md
* Adds the documentation for the new `Yoast\WP\SEO\should_index_indexables` filter.
* 
https://github.com/Yoast/developer-site/pull/133
=> Add docs for `Yoast\WP\SEO\should_index_indexables`

docs/shopify/integrations.md
Add documentation for Yoast Shopify integrations
https://github.com/Yoast/developer-site/pull/135
=> Add documentation for Yoast Shopify integrations

README.md
=> Djennez patch 1

docs/development/environment/tools.md
* Fixes the syntax of the `brew cask` command.
*
=> Update the syntax for the brew cask command.

docs/features/schema/api.md
* Adds documentation for the `wpseo_schema_graph` filter.
*
=> Add documentation for the `wpseo_schema_graph` filter.

docs/customization/yoast-seo/filters/disable-search-engine-pings.md
* Add docs about disabling the XML sitemap ping.
*
=> Add docs about disabling XML sitemap pings

docs/features/schema/api.md, docs/features/schema/functional-specification.md, docs/features/schema/integration-guidelines.md, docs/features/schema/pieces.md, docs/features/schema/pieces/aggregateoffer.md, docs/features/schema/pieces/article.md, docs/features/schema/pieces/breadcrumb.md, docs/features/schema/pieces/comment.md, docs/features/schema/pieces/howto.md, docs/features/schema/pieces/image.md, docs/features/schema/pieces/localbusiness.md, docs/features/schema/pieces/offer.md, docs/features/schema/pieces/organization.md, docs/features/schema/pieces/person.md, docs/features/schema/pieces/postaladdress.md, docs/features/schema/pieces/product.md, docs/features/schema/pieces/question.md, docs/features/schema/pieces/recipe.md, docs/features/schema/pieces/review.md, docs/features/schema/pieces/video.md, docs/features/schema/pieces/webpage.md, docs/features/schema/pieces/website.md, docs/features/schema/technology-approach.md
Our ID syntax was inconsistent in various ways; should all be clean and future-proof now.
=> Standardize IDs & misc fixes

README.md
=> test update - deploy
